apiVersion: v1
appVersion: 2.3.5
description: A Traefik based Kubernetes ingress controller with Let's Encrypt support
engine: gotpl
home: https://traefik.io/
icon: file://../traefik.logo.png
keywords:
- traefik
- ingress
- acme
- letsencrypt
maintainers:
- email: manuel@containo.us
  name: SantoDE
name: traefik
sources:
- https://github.com/traefik/traefik
version: 2.3.5
